#pragma once

#include <ros/ros.h>
#include <image_transport/image_transport.h>
#include <cv_bridge/cv_bridge.h>
#include <camera_info_manager/camera_info_manager.h>

#include "camplex/CameraDriver.h"

// Services auto-generated by ROS
#include "camplex/CaptureFrames.h"
#include "camplex/GetCameraInfo.h"
#include "camplex/PrintCapabilities.h"
#include "camplex/SetStreaming.h"

#include "paraset/ParameterManager.hpp"

#include "argus_utils/synchronization/SynchronizationTypes.h"
#include "argus_utils/synchronization/WorkerPool.h"

#include <memory>
#include <boost/thread/locks.hpp>
#include <deque>

namespace argus
{

/*! \brief ROS driver for a stereo camera that publishes concatenated
 * side-by-side images.
 */
class SplitStereoDriverNode
{
public:

	typedef std::shared_ptr<SplitStereoDriverNode> Ptr;

	SplitStereoDriverNode( ros::NodeHandle& nh, ros::NodeHandle& ph );
	~SplitStereoDriverNode();

private:

	WorkerPool _workers;

	// Service handlers
	ros::ServiceServer _leftInfoServer;
	ros::ServiceServer _rightInfoServer;    
	ros::ServiceServer _capabilitiesServer;
	ros::ServiceServer _setStreamingServer;

    ros::NodeHandle _leftNh;
    ros::NodeHandle _rightNh;

	image_transport::ImageTransport _leftIt;
	image_transport::ImageTransport _rightIt;
	image_transport::CameraPublisher _leftPub;
	image_transport::CameraPublisher _rightPub;

	camera_info_manager::CameraInfoManager _leftInfoManager;
	camera_info_manager::CameraInfoManager _rightInfoManager;
    
	sensor_msgs::CameraInfo::Ptr _leftInfo;
	sensor_msgs::CameraInfo::Ptr _rightInfo;

	/*! \brief Denotes the camera's mode of operation. */
	enum StreamingMode
	{
		STREAM_OFF,
		STREAM_CONTINUOUS,
	};

	mutable Mutex _mutex;
	ConditionVariable _blocked;
	StreamingMode _mode;

	std::string _cameraName;
	CameraDriver _driver;

	std::deque<NumericParam> _numericParams;
	std::deque<BooleanParam> _booleanParams;

	// Externally-locked functions to set the streaming state
	void StartStreaming( WriteLock& lock );
	void StopStreaming( WriteLock& lock );

	void IntControlCallback( int id, double value );
	void BoolControlCallback( int id, bool value );

	bool GetLeftInfoService( camplex::GetCameraInfo::Request& req,
	                         camplex::GetCameraInfo::Response& res );
    bool GetRightInfoService( camplex::GetCameraInfo::Request& req,
	                          camplex::GetCameraInfo::Response& res );

	bool SetStreamingService( camplex::SetStreaming::Request& req,
	                          camplex::SetStreaming::Response& res );

	bool PrintCapabilitiesService( camplex::PrintCapabilities::Request& req,
	                               camplex::PrintCapabilities::Response& res );

	void Spin();

};

}
